name = "lnnwppanel"
main = "_worker.js"
compatibility_date = "2026-01-10"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "65cf6d3c623c4232844bd081164c132d"				#KV数据库id1
[vars]
PASSWORD = "liwanxi521"
